/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.admin.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Fund service. Represents a row in the &quot;evp_Fund&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.evp.admin.model.impl.FundModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.evp.admin.model.impl.FundImpl}.
 * </p>
 *
 * @author Joan.Kim
 * @see Fund
 * @see com.liferay.evp.admin.model.impl.FundImpl
 * @see com.liferay.evp.admin.model.impl.FundModelImpl
 * @generated
 */
@ProviderType
public interface FundModel extends BaseModel<Fund>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fund model instance should use the {@link Fund} interface instead.
	 */

	/**
	 * Returns the primary key of this fund.
	 *
	 * @return the primary key of this fund
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fund.
	 *
	 * @param primaryKey the primary key of this fund
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fund ID of this fund.
	 *
	 * @return the fund ID of this fund
	 */
	public long getFundId();

	/**
	 * Sets the fund ID of this fund.
	 *
	 * @param fundId the fund ID of this fund
	 */
	public void setFundId(long fundId);

	/**
	 * Returns the group ID of this fund.
	 *
	 * @return the group ID of this fund
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this fund.
	 *
	 * @param groupId the group ID of this fund
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this fund.
	 *
	 * @return the company ID of this fund
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this fund.
	 *
	 * @param companyId the company ID of this fund
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this fund.
	 *
	 * @return the user ID of this fund
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this fund.
	 *
	 * @param userId the user ID of this fund
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fund.
	 *
	 * @return the user uuid of this fund
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this fund.
	 *
	 * @param userUuid the user uuid of this fund
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fund.
	 *
	 * @return the user name of this fund
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this fund.
	 *
	 * @param userName the user name of this fund
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fund.
	 *
	 * @return the create date of this fund
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this fund.
	 *
	 * @param createDate the create date of this fund
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fund.
	 *
	 * @return the modified date of this fund
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fund.
	 *
	 * @param modifiedDate the modified date of this fund
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the project ID of this fund.
	 *
	 * @return the project ID of this fund
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this fund.
	 *
	 * @param projectId the project ID of this fund
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the amount of this fund.
	 *
	 * @return the amount of this fund
	 */
	public double getAmount();

	/**
	 * Sets the amount of this fund.
	 *
	 * @param amount the amount of this fund
	 */
	public void setAmount(double amount);

	/**
	 * Returns the volunteer ID of this fund.
	 *
	 * @return the volunteer ID of this fund
	 */
	public long getVolunteerId();

	/**
	 * Sets the volunteer ID of this fund.
	 *
	 * @param volunteerId the volunteer ID of this fund
	 */
	public void setVolunteerId(long volunteerId);

	/**
	 * Returns the receive date of this fund.
	 *
	 * @return the receive date of this fund
	 */
	public Date getReceiveDate();

	/**
	 * Sets the receive date of this fund.
	 *
	 * @param receiveDate the receive date of this fund
	 */
	public void setReceiveDate(Date receiveDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.evp.admin.model.Fund fund);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.evp.admin.model.Fund> toCacheModel();

	@Override
	public com.liferay.evp.admin.model.Fund toEscapedModel();

	@Override
	public com.liferay.evp.admin.model.Fund toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}