/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.admin.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Project service. Represents a row in the &quot;evp_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.evp.admin.service.model.impl.ProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.evp.admin.service.model.impl.ProjectImpl}.
 * </p>
 *
 * @author Joan.Kim
 * @see Project
 * @see com.liferay.evp.admin.service.model.impl.ProjectImpl
 * @see com.liferay.evp.admin.service.model.impl.ProjectModelImpl
 * @generated
 */
@ProviderType
public interface ProjectModel extends BaseModel<Project>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project model instance should use the {@link Project} interface instead.
	 */

	/**
	 * Returns the primary key of this project.
	 *
	 * @return the primary key of this project
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project.
	 *
	 * @param primaryKey the primary key of this project
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the project ID of this project.
	 *
	 * @return the project ID of this project
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project.
	 *
	 * @param projectId the project ID of this project
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the group ID of this project.
	 *
	 * @return the group ID of this project
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this project.
	 *
	 * @param groupId the group ID of this project
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this project.
	 *
	 * @return the company ID of this project
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project.
	 *
	 * @param companyId the company ID of this project
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this project.
	 *
	 * @return the user ID of this project
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this project.
	 *
	 * @param userId the user ID of this project
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this project.
	 *
	 * @return the user uuid of this project
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this project.
	 *
	 * @param userUuid the user uuid of this project
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this project.
	 *
	 * @return the user name of this project
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this project.
	 *
	 * @param userName the user name of this project
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this project.
	 *
	 * @return the create date of this project
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this project.
	 *
	 * @param createDate the create date of this project
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project.
	 *
	 * @return the modified date of this project
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project.
	 *
	 * @param modifiedDate the modified date of this project
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this project.
	 *
	 * @return the name of this project
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this project.
	 *
	 * @param name the name of this project
	 */
	public void setName(String name);

	/**
	 * Returns the description of this project.
	 *
	 * @return the description of this project
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this project.
	 *
	 * @param description the description of this project
	 */
	public void setDescription(String description);

	/**
	 * Returns the location of this project.
	 *
	 * @return the location of this project
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this project.
	 *
	 * @param location the location of this project
	 */
	public void setLocation(String location);

	/**
	 * Returns the coord x of this project.
	 *
	 * @return the coord x of this project
	 */
	public long getCoordX();

	/**
	 * Sets the coord x of this project.
	 *
	 * @param coordX the coord x of this project
	 */
	public void setCoordX(long coordX);

	/**
	 * Returns the coord y of this project.
	 *
	 * @return the coord y of this project
	 */
	public long getCoordY();

	/**
	 * Sets the coord y of this project.
	 *
	 * @param coordY the coord y of this project
	 */
	public void setCoordY(long coordY);

	/**
	 * Returns the cover image ID of this project.
	 *
	 * @return the cover image ID of this project
	 */
	public long getCoverImageId();

	/**
	 * Sets the cover image ID of this project.
	 *
	 * @param coverImageId the cover image ID of this project
	 */
	public void setCoverImageId(long coverImageId);

	/**
	 * Returns the required funds of this project.
	 *
	 * @return the required funds of this project
	 */
	public double getRequiredFunds();

	/**
	 * Sets the required funds of this project.
	 *
	 * @param requiredFunds the required funds of this project
	 */
	public void setRequiredFunds(double requiredFunds);

	/**
	 * Returns the actual funds of this project.
	 *
	 * @return the actual funds of this project
	 */
	public double getActualFunds();

	/**
	 * Sets the actual funds of this project.
	 *
	 * @param actualFunds the actual funds of this project
	 */
	public void setActualFunds(double actualFunds);

	/**
	 * Returns the start date of this project.
	 *
	 * @return the start date of this project
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this project.
	 *
	 * @param startDate the start date of this project
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this project.
	 *
	 * @return the end date of this project
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this project.
	 *
	 * @param endDate the end date of this project
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the approval date of this project.
	 *
	 * @return the approval date of this project
	 */
	public Date getApprovalDate();

	/**
	 * Sets the approval date of this project.
	 *
	 * @param approvalDate the approval date of this project
	 */
	public void setApprovalDate(Date approvalDate);

	/**
	 * Returns the manager name of this project.
	 *
	 * @return the manager name of this project
	 */
	@AutoEscape
	public String getManagerName();

	/**
	 * Sets the manager name of this project.
	 *
	 * @param managerName the manager name of this project
	 */
	public void setManagerName(String managerName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.evp.admin.service.model.Project project);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.evp.admin.service.model.Project> toCacheModel();

	@Override
	public com.liferay.evp.admin.service.model.Project toEscapedModel();

	@Override
	public com.liferay.evp.admin.service.model.Project toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}