/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.admin.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Volunteer service. Represents a row in the &quot;evp_Volunteer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.evp.admin.service.model.impl.VolunteerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.evp.admin.service.model.impl.VolunteerImpl}.
 * </p>
 *
 * @author Joan.Kim
 * @see Volunteer
 * @see com.liferay.evp.admin.service.model.impl.VolunteerImpl
 * @see com.liferay.evp.admin.service.model.impl.VolunteerModelImpl
 * @generated
 */
@ProviderType
public interface VolunteerModel extends BaseModel<Volunteer>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a volunteer model instance should use the {@link Volunteer} interface instead.
	 */

	/**
	 * Returns the primary key of this volunteer.
	 *
	 * @return the primary key of this volunteer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this volunteer.
	 *
	 * @param primaryKey the primary key of this volunteer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the volunteer ID of this volunteer.
	 *
	 * @return the volunteer ID of this volunteer
	 */
	public long getVolunteerId();

	/**
	 * Sets the volunteer ID of this volunteer.
	 *
	 * @param volunteerId the volunteer ID of this volunteer
	 */
	public void setVolunteerId(long volunteerId);

	/**
	 * Returns the group ID of this volunteer.
	 *
	 * @return the group ID of this volunteer
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this volunteer.
	 *
	 * @param groupId the group ID of this volunteer
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this volunteer.
	 *
	 * @return the company ID of this volunteer
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this volunteer.
	 *
	 * @param companyId the company ID of this volunteer
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this volunteer.
	 *
	 * @return the user ID of this volunteer
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this volunteer.
	 *
	 * @param userId the user ID of this volunteer
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this volunteer.
	 *
	 * @return the user uuid of this volunteer
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this volunteer.
	 *
	 * @param userUuid the user uuid of this volunteer
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this volunteer.
	 *
	 * @return the user name of this volunteer
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this volunteer.
	 *
	 * @param userName the user name of this volunteer
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this volunteer.
	 *
	 * @return the create date of this volunteer
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this volunteer.
	 *
	 * @param createDate the create date of this volunteer
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this volunteer.
	 *
	 * @return the modified date of this volunteer
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this volunteer.
	 *
	 * @param modifiedDate the modified date of this volunteer
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this volunteer.
	 *
	 * @return the first name of this volunteer
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this volunteer.
	 *
	 * @param firstName the first name of this volunteer
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this volunteer.
	 *
	 * @return the last name of this volunteer
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this volunteer.
	 *
	 * @param lastName the last name of this volunteer
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the address of this volunteer.
	 *
	 * @return the address of this volunteer
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this volunteer.
	 *
	 * @param address the address of this volunteer
	 */
	public void setAddress(String address);

	/**
	 * Returns the coord x of this volunteer.
	 *
	 * @return the coord x of this volunteer
	 */
	public long getCoordX();

	/**
	 * Sets the coord x of this volunteer.
	 *
	 * @param coordX the coord x of this volunteer
	 */
	public void setCoordX(long coordX);

	/**
	 * Returns the coord y of this volunteer.
	 *
	 * @return the coord y of this volunteer
	 */
	public long getCoordY();

	/**
	 * Sets the coord y of this volunteer.
	 *
	 * @param coordY the coord y of this volunteer
	 */
	public void setCoordY(long coordY);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.evp.admin.service.model.Volunteer volunteer);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.evp.admin.service.model.Volunteer> toCacheModel();

	@Override
	public com.liferay.evp.admin.service.model.Volunteer toEscapedModel();

	@Override
	public com.liferay.evp.admin.service.model.Volunteer toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}